### ISSUE TITLE
Class email.EmailModule does not exist

### ISSUE THREAD

**Issue by iceman2hot4u** [cornernote/yii-email-module#11]
So, I installed the module but I get this error when I'm trying to access 'www.mysite.com/email'.

My main.php config for the email module is:

`    
'aliases' => array(
        'vendor' => '/../../vendor',
        'email' => 'vendor/cornernote/yii-email-module/email',
    ),
    'modules' => array(
        'email' => array(
            'class' => 'email.EmailModule',
            'adminUsers' => array('@'),
            'autoCreateTables' => true,
            'connectionID' => 'db',
        ),
    ),
`

I am using Yii2 Advanced Template.

Do you have any idea why I have this error?

**Comment by cornernote** [comment]
This module is for yii1

**Comment by iceman2hot4u** [comment]
Oh, I'm stupid. Thank you.

**Comment by cornernote** [comment]
No problem, I found yii2 has pretty good built in email functionality so I
haven't ported this

**Comment by iceman2hot4u** [comment]
I know. I was looking for something with an UI. 
Guess I need to make it myself. 
Thank you.

**Comment by cornernote** [comment]
A UI for managing the templates? I prefer them to be php, but being
mustache in the db was good because users could modify them... Maybe I'll
reconsider porting this at some stage

**Comment by iceman2hot4u** [comment]
Yes. I need to make an UI for managing the templates. I will make them php and add some available variables so that the user can modify them.

**Comment by cornernote** [comment]
Storing php in the database rings security alarms in my head. I recommend
using mustache or some other template language
